apiVersion: v1
kind: Secret
metadata:
  name: rp-api-backend-secret
  namespace: rotten-potatoes
type: Opaque
data:
  ConnectionStrings__DefaultConnection: SG9zdD1ycC1kYi1wb3N0Z3JlcztEYXRhYmFzZT1yb3R0ZW47VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9Y2hhbmdlbWU=