apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: rotten-potatoes
  labels:
    app: rp-db-postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
