apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: rotten-potatoes
  labels:
    type: local
    app: rp-db-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql