apiVersion: v1
kind: Secret
metadata:
  name: rp-db-secret
  namespace: rotten-potatoes
  labels:
    app: rp-db-postgres
type: Opaque
data:
  POSTGRES_DB: cm90dGVu
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: Y2hhbmdlbWU=
