apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-db-postgres
  namespace: rotten-potatoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rp-db-postgres
  template:
    metadata:
      labels:
        app: rp-db-postgres
    spec:
      containers:
        - name: rp-db-postgres
          image: 'postgres:13'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
